[package]
name = "okf-prepare-core"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
comrak = { version = "=0.55.0", default-features = false }
finl_unicode = { version = "=1.4.0", default-features = false, features = ["categories"] }
saphyr = { version = "=0.0.12", default-features = false }
time = { version = "=0.3.45", default-features = false }
unicode-normalization = { version = "=0.1.25", default-features = false }
