/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Native search handle. The public TypeScript adapter should keep accepting
 * raw Markdown and use the existing OKF parser/projector before crossing this
 * boundary.
 */
export declare class NativeOkfSearch {
  static fromPrepared(documents: Array<PreparedDocument>): NativeOkfSearch
  ingestPrepared(document: PreparedDocument): void
  removeDocument(documentId: string): boolean
  search(query: string, options?: SearchOptions | undefined | null): Array<SearchHit>
  indexStats(): IndexStats
  listTypes(): Array<string>
  listDegradedDocuments(): Array<DegradedDocument>
  /**
   * Tantivy exposes the pieces needed to build completion, but not the
   * section-aware MiniSearch `autoSuggest` contract. Returning ordinary
   * search hits as suggestions would be misleading, so this spike fails
   * explicitly instead.
   */
  autoSuggest(query: string, options?: SearchOptions | undefined | null): Array<Suggestion>
}

export interface DegradedDocument {
  documentId: string
  path: string
  diagnostics: Array<Diagnostic>
}

export interface Diagnostic {
  code: string
  message: string
  field?: string
  path: string
}

export interface IndexDocumentStats {
  total: number
  strict: number
  degraded: number
}

export interface IndexStats {
  logical: LogicalIndexStats
  storage: IndexStorageStats
}

export interface IndexStatusStats {
  draft: number
  stable: number
  deprecated: number
  unclassified: number
}

export interface IndexStorageStats {
  kind: "in-memory-index-files"
  sizeInBytes: number
}

export interface IndexTrustTierStats {
  unverified: number
  machineConfirmed: number
  humanReviewed: number
  unclassified: number
}

export interface IndexTypeStats {
  type: string
  documentCount: number
}

export interface LogicalIndexStats {
  documents: IndexDocumentStats
  types: Array<IndexTypeStats>
  statuses: IndexStatusStats
  trustTiers: IndexTrustTierStats
}

export interface PreparedDocument {
  documentId: string
  path: string
  type: string
  conformance: string
  diagnostics: Array<Diagnostic>
  title: string
  tags: Array<string>
  status?: string
  staleAfterEpoch?: number
  stalenessClassified: boolean
  trustTier?: string
  resource: string
  description: string
  sourceText: string
  sections: Array<PreparedSection>
}

/** Search-independent output from the existing OKF parser/projector. */
export interface PreparedSection {
  sectionId: string
  headingPath: string
  text: string
  startLine: number
  endLine: number
}

export interface SearchBoost {
  resource?: number
  title?: number
  heading?: number
  description?: number
  tags?: number
  type?: number
  sources?: number
  body?: number
}

export interface SearchHit {
  documentId: string
  title: string
  sectionId: string
  score: number
  conformance: string
  matchedFields: Array<string>
  headingPath: string
  path: string
  startLine: number
  endLine: number
  snippet: string
}

export interface SearchOptions {
  limit?: number
  where?: SearchWhere
  asOf?: Date
  match?: string
  fields?: Array<string>
  boost?: SearchBoost
  fuzzy?: boolean | number
}

export interface SearchWhere {
  types?: Array<string>
  tagsAny?: Array<string>
  statuses?: Array<string>
  trustTiers?: Array<string>
  stale?: boolean
  conformance?: Array<string>
}

export interface Suggestion {
  suggestion: string
  terms: Array<string>
  score: number
}
